services:
  scheduler:
    build: scheduler/.
  storefront:
    build: storefront/.
  database:
    image: "mysql"
    env_file:
      - ./mysql/env_vars
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
      - kineteco:/var/lib/mysql:rw
volumes:
  - kineteco